 on: push
 name: Reactor done
 jobs:
   build-job:
     name: Build .NET project
     runs-on: ubuntu-latest
     container: mcr.microsoft.com/dotnet/sdk:6.0
     steps:
       -  run: dotnet --version
          name: Check dotnet version
       -  uses: actions/checkout@v3
          name: Checkout Code
       -  run: |
            dotnet publish
            --configuration Release
            --output out
          name: Publish .NET web application
             